### ISSUE TITLE
Missing OpenVINO's and EdgeX's license and copyright

### ISSUE THREAD

**Issue by MonicaisHer** [canonical/edgex-demos#8]
This repo is missing OpenVINO's and EdgeX's licenses and the appropriate copyright notice.
The dockerfile also needs to include OpenVINO's license.

**Comment by MonicaisHer** [comment]
Could we added the openvino's licensing folder to edgex-openvino-object-detection folder? 
https://github.com/openvinotoolkit/openvino/blob/master/licensing/third-party-programs.txt

**Comment by MonicaisHer** [comment]
YOLO model's license: https://docs.openvino.ai/latest/omz_models_model_yolo_v2_tiny_tf.html#legal-information

**Comment by farshidtz** [comment]
Added by #9 and 595c879ac70c924b3042fef0e49ccc543c2aa431.
